### ISSUE TITLE
Error en rake post

### ISSUE THREAD

**Issue by andreshp** [dgiim/blog#99]
Al hacer `rake post` e introducir los correspondientes datos se produce el siguiente error:

~~~
Post name: Longest Increasing Subsequence
Author (andreshp): andreshp
Category: algoritmos
Switched to branch 'post-longest-increasing-subsequence'
rake aborted!
Git::GitExecuteError: git '--git-dir=/home/andreshp/SeminariosDobleGrado/blog/.git' '--work-tree=/home/andreshp/SeminariosDobleGrado/blog' commit '--message=[longest-increasing-subsequence] New post' '--all'  2>&1:On branch post-longest-increasing-subsequence
Untracked files:
	_posts/2015-09-20-longest-increasing-subsequence.md

nothing added to commit but untracked files present/var/lib/gems/2.1.0/gems/git-1.2.9.1/lib/git/lib.rb:917:in `command'
/var/lib/gems/2.1.0/gems/git-1.2.9.1/lib/git/lib.rb:540:in `commit'
/var/lib/gems/2.1.0/gems/git-1.2.9.1/lib/git/base.rb:301:in `commit_all'
/home/andreshp/SeminariosDobleGrado/blog/Rakefile:77:in `block in <top (required)>'
Tasks: TOP => post
(See full trace by running task with --trace)
~~~

La rama se ha creado con el archivo .md en local pero falla al crear la rama en GitHub.

**Comment by M42** [comment]
Reproduzco el error:
```
rake post
Post name: StackExchange
Author (mario): M42
Category: Utilidades
Switched to branch 'post-stackexchange'
rake aborted!
Git::GitExecuteError: git '--git-dir=/home/mario/Projects/blog/.git' '--work-tree=/home/mario/Projects/blog' commit '--message=[stackexchange] New post' '--all'  2>&1:On branch post-stackexchange
Untracked files:
	_posts/2015-12-22-stackexchange.md

nothing added to commit but untracked files present/home/mario/.rvm/gems/ruby-2.1.1/gems/git-1.2.9.1/lib/git/lib.rb:917:in `command'
/home/mario/.rvm/gems/ruby-2.1.1/gems/git-1.2.9.1/lib/git/lib.rb:540:in `commit'
/home/mario/.rvm/gems/ruby-2.1.1/gems/git-1.2.9.1/lib/git/base.rb:301:in `commit_all'
/home/mario/Projects/blog/Rakefile:77:in `block in <top (required)>'
/home/mario/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/home/mario/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => post
(See full trace by running task with --trace)
```

**Comment by JJ** [comment]
¿Falta un git add?

**Comment by fdavidcl** [comment]
@JJ Efectivamente, pero al parecer antes funcionaba sin el 'git add' :confused:
